#### Q1. What are the benefits of the built-in array package, if any?
**Ans:** 

Arrays represent multiple data items of the same type using a single name.

In arrays, the elements can be accessed randomly by using the index number. 

Arrays allocate memory in contiguous memory locations for all its elements. Hence there is no chance of extra memory being allocated in case of arrays. This avoids memory overflow or shortage of memory in arrays.

In [2]:
#Example
from array import array

# Create an array of integers
int_array = array('i', [1, 2, 3, 4, 5])

# Access elements
print(int_array[0])  # Output: 1

# Append elements
int_array.append(6)

# Print the entire array
print(int_array)  # Output: array('i', [1, 2, 3, 4, 5, 6])


1
array('i', [1, 2, 3, 4, 5, 6])


#### Q2. What are some of the array package's limitations ?
**Ans:**  The number of elements to be stored in an array should be known in advance. An array is a static structure (which means the array is of fixed size). Once declared the size of the array cannot be modified. The memory which is allocated to it cannot be increased or decreased.

Insertion and deletion are quite difficult in an array as the elements are stored in consecutive memory locations and the shifting operation is costly.

Arrays store homogeneous data types ie; all items must be of same data type.

#### Q3. Describe the main differences between the array and numpy packages ?
**Ans:**  

The key differences are:

**1. Functionality and Versatility:**

The array module is part of the Python standard library and provides a basic array implementation with limited functionality. It is primarily designed for storing arrays of numeric values.

numpy is a powerful third-party library specifically designed for numerical operations. It provides a multidimensional array object (numpy.ndarray) with a vast array of functions and operations for mathematical and logical operations.



**2. Data Types:**

The array module is limited to one-dimensional arrays and requires all elements to be of the same data type.

numpy arrays can be multidimensional and support a wide range of data types. This flexibility is especially useful when dealing with complex numerical data.


**3. Memory Efficiency:**

numpy arrays are more memory-efficient than array objects, especially for large datasets. numpy arrays are implemented in C and allow for efficient storage and manipulation of large amounts of numerical data.


**4. Broadcasting:**

One of the powerful features of numpy is broadcasting. It allows operations on arrays of different shapes and sizes, making it easier to perform element-wise operations without the need for explicit looping.

**5. Ease of Use:**

numpy provides a more user-friendly and convenient interface for working with arrays, offering a wide range of mathematical functions and operations.
The array module is more basic and lacks many of the advanced features and functions provided by numpy.


#### Q4. Explain the distinctions between the empty, ones, and zeros functions ?
**Ans:** The empty, ones, and zeros functions are related to array creation and manipulation using NumPy. Here are the distinctions between these functions:

1. numpy.empty: Creates an array without initializing its elements to any particular values.

2. numpy.ones: Creates an array filled with ones.

3. numpy.zeros: Creates an array filled with zeros.

In [3]:
#Example
import numpy as np

empty_array = np.empty((3, 3))
print(empty_array)

ones_array = np.ones((2, 2))
print(ones_array)

zeros_array = np.zeros((2, 2))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


#### Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument ?
**Ans:**  In the numpy.fromfunction function, the callable argument is a function that is called with coordinates as arguments to compute the values of the array. 

**Syntax:**

numpy.fromfunction(function, shape, **kwargs)

function: A callable object (usually a function) that is called with N parameters, where N is the rank of the array (the number of dimensions). The function should return the value of the array at a given set of coordinates.

shape: The shape of the output array.

**kwargs: Additional keyword arguments that are passed to the function.

In [5]:
#Example
import numpy as np

# Define a function that computes the value based on coordinates
def my_function(x, y):
    return x + y

# Create a 3x3 array using the function
result_array = np.fromfunction(my_function, (3, 3), dtype=int)

print(result_array)


[[0 1 2]
 [1 2 3]
 [2 3 4]]


In above example, the my_function function takes two parameters x and y, representing the coordinates of the array elements. The function returns the sum of x and y. The numpy.fromfunction then uses this function to create a 3x3 array by computing the values for each element based on their coordinates.

#### Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression `A + n` ?
**Ans:** When a NumPy array is combined with a single-value operand (a scalar) through addition, each element of the array is incremented by the scalar value. This operation is known as scalar addition, and it is applied element-wise.

In [6]:
import numpy as np

# Create a NumPy array
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Scalar addition
n = 10
result_array = A + n

print(result_array)


[[11 12 13]
 [14 15 16]
 [17 18 19]]


#### Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome ?
**Ans:** Yes, array-to-scalar operations in NumPy can use combined operation-assign operators, such as += or *=. When we use these operators, the operation is performed in-place(to each element), modifying the original array.

In [8]:
#Example
import numpy as np

# Create a NumPy array
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# In-place addition with a scalar
n = 10
A += n

print(A)

print()

# In-place multiplication with a scalar
A *= 2

print(A)



[[11 12 13]
 [14 15 16]
 [17 18 19]]

[[22 24 26]
 [28 30 32]
 [34 36 38]]


#### Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays ?
**Ans:** : In NumPy, we can create arrays of fixed-length strings using the numpy.string_ or numpy.str_(default) data type. However, it's important to note that these arrays will not dynamically resize to accommodate longer strings. 

If we allocate a longer string to an element in a fixed-length string array, the extra characters beyond the specified length will be truncated.

In [13]:
import numpy as np

# Create a NumPy array of fixed-length strings
string_array = np.array(['apple', 'banana', 'cherry'],dtype=np.string_)
#or string_array = np.array(['apple', 'banana', 'cherry'])

# Print the original array
print("Original array:")
print(string_array)

# Attempt to allocate a longer string
string_array[1] = 'grapefruit'

# Print the modified array
print("\nModified array:")
print(string_array)



Original array:
[b'apple' b'banana' b'cherry']

Modified array:
[b'apple' b'grapef' b'cherry']


#### Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays ?
**Ans:** When we combine two NumPy arrays using an operation like addition (+) or multiplication (*), the operation is performed element-wise. 

Here are the conditions for combining two NumPy arrays:


**1. Shape Compatibility:**

The arrays must have compatible shapes for the operation to be valid.<br/>
For addition, subtraction, and element-wise multiplication or division, the arrays must have the same shape or be broadcastable to the same shape.<br/>
Broadcasting allows NumPy to perform operations on arrays of different shapes and sizes by implicitly expanding smaller arrays to match the shape of larger ones.<br/>

**2. Compatible Data Types:**

The data types of the arrays should be compatible. For example, you can add two arrays with integer elements or two arrays with floating-point elements. NumPy will perform element-wise operations with the common data type.

In [14]:
#Example
import numpy as np

# Example arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[10, 20, 30],
                 [40, 50, 60]])

# Addition
result_addition = arr1 + arr2

# Multiplication
result_multiplication = arr1 * arr2

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)

print("\nResult of Addition:")
print(result_addition)

print("\nResult of Multiplication:")
print(result_multiplication)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[10 20 30]
 [40 50 60]]

Result of Addition:
[[11 22 33]
 [44 55 66]]

Result of Multiplication:
[[ 10  40  90]
 [160 250 360]]


In above example, element-wise addition and multiplication are performed on the two arrays because they have compatible shapes. If the shapes were incompatible and could not be broadcasted, a ValueError would be raised.

#### Q10. What is the best way to use a Boolean array to mask another array ?
**Ans:** The best way to use a Boolean array to mask another array is by Using `masked_where` of numpy package.

In [15]:
import numpy as np
import numpy.ma as ma

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Create a mask based on a condition
mask_condition = arr > 3

# Use masked_where to mask elements based on the condition
masked_arr = ma.masked_where(mask_condition, arr)

print("Original Array:", arr)
print("Masked Array:", masked_arr)


Original Array: [1 2 3 4 5]
Masked Array: [1 2 3 -- --]


In above example, the mask_condition is created such that it is True for elements greater than 3. The masked_arr is then created using numpy.ma.masked_where, which masks elements where the condition is True.

#### Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute ?
**Ans:** Here are three different ways to calculate the standard deviation of a wide collection of data using standard Python and its packages, sorted by their likely execution speed:

**1. Using NumPy:** NumPy is highly optimized for numerical operations and is likely to be the fastest.

In [25]:
import numpy as np

data = [x for x in range(1,101)]  
std_dev = np.std(data)
print(std_dev)

28.86607004772212


**2. Using the statistics module (Standard Python Library):** Comes with the standard Python library, no need for additional installations.

In [24]:
import statistics

data = [x for x in range(1,101)]  
std_dev = statistics.stdev(data)
print(std_dev)


29.011491975882016


**3. Using a Custom Calculation (Standard Python):** No need for external libraries, especially useful for smaller datasets.

In [26]:
data = [x for x in range(1,101)]
mean = sum(data) / len(data)
variance = sum((x - mean) ** 2 for x in data) / len(data)
std_dev = variance ** 0.5
print(std_dev)

28.86607004772212


#### 12. What is the dimensionality of a Boolean mask-generated array ?
**Ans:**  It will have same dimensionality as input array.

In [16]:
import numpy as np
import numpy.ma as ma

# Create a 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Create a mask condition for elements greater than 5
mask_condition = arr_2d > 5

# Create a masked array using masked_where
masked_arr_2d = ma.masked_where(mask_condition, arr_2d)

print("Original 2D Array:")
print(arr_2d)

print("\nMasked Array:")
print(masked_arr_2d)


Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Masked Array:
[[1 2 3]
 [4 5 --]
 [-- -- --]]


Here the dimensionality of the both array remains 2D.